const ingame_rules = [
    'everyone go to x lane',
    'invade the enemy jungle right now',
    'die to tower',
    'buy x item',
    'jungler must announce their next gank in all chat and commit to it',
    'stay under your tower for the next minute. Do not leave under any circumstance. Jungle must go to top lane tower.',
    'Everyone recall',
    'Everyone recall and stay in fountain for 30 seconds',
    'Demand a 5v5 in baron pit. If the enemy does not respond, then go to baron pit and wait till someone shows up or the next rule is made',
    'stay in the river for the next minute',
    'everyone swap lanes',
    'find the enemy jungler and kill then',
    'contest every dragon or baron for the rest of the game',
    'adc and support reverse roles for the next 3 minutes',
    'take a jungle camp. If your jungle does not have enough, take an enemy camp',
    'pick one player to 1v1 their laning opponent in the baron pit',
    'for the next 3 minutes, only play inside the jungle or river. No one can be in a lane. Do not cross from one side to another',
    'choose one player to be the designated warder. no one else is allowed to use any type of ward',
    'for the next 3 minutes, no one is allowed to jungle or step into the river',
    'if you need to recall, you must run all the way back to fountain. Do not recall',
    'Jungler must attempt to solo baron',
    'everyone ult right now',
    'everyone tower dive right now',
    'touch the enemy tower and then touch your tower',
    'meat shield: choose one person on your team and protect them. No skills. if they die, sell all items and buy new ones',
    'dance party for the next 4 seconds',
    'mouse only for the next minute',
    'take revenge on the mext person who killed someone on your team',
    'if dead before the next rule, then only buy items < 500 gold',
    'skillshots only for the next minute',
    'buffs only for next minute',
    'do not cs for the next 30 seconds',
    'burn a summoner',
    'if using discord or league voice, disconnect for x amount of time (or rest of match)',
    'sell your most expensive item and buy a new item (cannot be component of the one you just sold',
    'do not ult for the next 5 minutes',
    'only use chicken noises to communicate for the next 2 minutes',
    "only talk in your champion's voice for the next 2 minutes",
    'no cc for the next 2 minutes',
    'if the enemy initiates a fight or a trade, fight them to the death'
]

export default ingame_rules